version: '3'
services:
  postgres:
    image: "postgres:9.4"
    ports:
    - "5433:5432"
    volumes:
    - db-data:/var/lib/postgresql/data
    - ./sql:/docker-entrypoint-initdb.d/
volumes:
  db-data:
