version: '3'
services:
  proxy:
    container_name: "nginx_proxy"
    image: "nginx:1.13.9-alpine"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - front
  web:
    build: .
    ports:
      - "8080:4567"
    restart: always
    networks:
      - front
      - back
  postgres:
    image: "postgres:10.3-alpine"
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d/
    networks:
      - back
volumes:
  db-data:
networks:
  front:
  back:
